DROP TABLE IF EXISTS SELL;


DROP TABLE IF EXISTS COFFEES;


DROP TABLE IF EXISTS COFFEEHOUSES;


CREATE TABLE COFFEES(
	NAME VARCHAR(20) PRIMARY KEY,
	MANUFACTURER VARCHAR(20)
);
CREATE TABLE COFFEEHOUSES(
	NAME VARCHAR(20) PRIMARY KEY,
	ADDRESS VARCHAR(30),
	LICENSE VARCHAR(30)
);

ALTER TABLE COFFEEHOUSES
ADD NUMBEROFGUESTS INTEGER;

CREATE TABLE SELLS(
	COFFEEHOUSE VARCHAR(20) REFERENCES COFFEEHOUSES(NAME),
	COFFEE VARCHAR(20) REFERENCES COFFEES(NAME),
	PRICE REAL,
	PRIMARY KEY (COFFEEHOUSE, COFFEE)
)