DROP TABLE IF EXISTS Projects0;
DROP TABLE IF EXISTS Projects4;
DROP TABLE IF EXISTS Projects3;
DROP TABLE IF EXISTS Projects2;
DROP TABLE IF EXISTS Projects1;

CREATE TABLE Projects1(
    MID INT PRIMARY KEY,
    MN VARCHAR(50) NOT NULL
);

CREATE TABLE Projects2(
    ID INT PRIMARY KEY,
    MID INT NOT NULL REFERENCES Projects1(MID)
);

CREATE TABLE Projects3(
    PID INT PRIMARY KEY,
    PN VARCHAR(50) NOT NULL
);

CREATE TABLE Projects4(
    SID INT PRIMARY KEY,
    SN VARCHAR(50) NOT NULL
);

CREATE TABLE Projects0(
    ID INT NOT NULL REFERENCES Projects2(ID),
    PID INT NOT NULL REFERENCES Projects3(PID),
    SID INT NOT NULL REFERENCES Projects4(SID),
    PRIMARY KEY (ID, PID, SID)
);

INSERT INTO Projects1
SELECT distinct MID, MN
FROM Projects;

INSERT INTO Projects2
SELECT distinct ID, MID
FROM Projects;

INSERT INTO Projects3
SELECT distinct PID, PN
FROM Projects;

INSERT INTO Projects4
SELECT distinct SID, SN
FROM Projects;

INSERT INTO Projects0
SELECT distinct ID, PID, SID
FROM Projects;